using MaintenanceJournal.ViewModels;

using System;
using System.Windows;

namespace MaintenanceJournal.Views
{
	/// <summary>
	/// Interaction logic for FallenRainWindow.xaml
	/// </summary>
	public partial class FallenRainWindow : Window
	{
		public FallenRainWindow(FallenRainViewModel fallenRainVM)
		{
			InitializeComponent();
		}

		private void FallenRainDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			for (int i = 1; i < FallenRainDataGrid.Columns.Count; i++)
			{
				FallenRainDataGrid.Columns[i].MinWidth = 50;
			}
		}
	}
}
